---
# ===============================
# Kubernetes Repository + Install
# ===============================

- name: Create Kubernetes keyring directory
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Download Kubernetes GPG key
  get_url:
    url: https://pkgs.k8s.io/core:/stable:/v1.34/deb/Release.key
    dest: /etc/apt/keyrings/kubernetes.asc
    mode: '0644'

- name: Add Kubernetes APT repository
  apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/kubernetes.asc] https://pkgs.k8s.io/core:/stable:/v1.34/deb/ /"
    state: present
    filename: kubernetes

- name: Install Kubernetes tools
  apt:
    name:
      - kubeadm
      - kubelet
      - kubectl
    update_cache: yes
    state: present

- name: Hold Kubernetes packages
  dpkg_selections:
    name: "{{ item }}"
    selection: hold
  loop:
    - kubeadm
    - kubelet
    - kubectl

# ==========
# Install Helm
# ==========

- name: Install Helm via script
  shell: |
    curl -fsSL https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
  args:
    creates: /usr/local/bin/helm
